# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a1baca6434cec71b2ebfefc9067d5b9eb85024b4041fdd18a9c5439d46cd7fc46d71f13ea6adf42ebad64ca61a7abb0583685f225c43d1d76335069ab029cf2

test:
  secret_key_base: a4868f3849271d392b77895c3cafcef0c640dbcc2f5ac9d08ad4cf4bd7764e6aa288189c6dc042526f89552485143f7e8c859071b885d4cb4ce8e276001514d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
